### ISSUE TITLE
Error trying to reproduce example from B-Series paper

### ISSUE THREAD

**Issue by ketch** [ranocha/BSeries.jl#106]
(posting on behalf of someone else, who is using Julia 1.8)

```
using BSeries, SymPy, Latexify
α = symbols("α", real=true)
```
yields
```
ERROR: cannot assign a value to variable RootedTrees.α from module Main
Stacktrace:
 [1] top-level scope
   @ REPL[24]:1
```

**Comment by ketch** [comment]
I'm not able to reproduce this in my own Juila environment.  I understand the error, but I don't know how Julia decides whether α is a new variable or a reference to the RootedTrees variable of the same name.

**Comment by ketch** [comment]
Okay, I've figured out how to reproduce it.  But there's a strange catch.  Each of the following is from a fresh REPL.
<img width="535" alt="Screen Shot 2023-03-08 at 8 24 27 AM" src="https://user-images.githubusercontent.com/697763/223626731-7e201b60-e487-4720-abf9-438dbfac5f3c.png">



<img width="218" alt="Screen Shot 2023-03-08 at 8 24 54 AM" src="https://user-images.githubusercontent.com/697763/223626793-f35aac73-0926-434d-80c1-a72f45b6fa3a.png">

 In my opinion, this is a bug in the Julia language.

**Comment by ranocha** [comment]
That's basically https://stackoverflow.com/a/56822954/11986942. If a function has been used in any way in the global scope, it cannot be re-assigned there. This is explained in the first section of https://docs.julialang.org/en/v1/manual/variables/. I do not judge whether this is the best behavior and do not know every discussion that led to this decision, but it is at least documented.

**Comment by ranocha** [comment]
The only thing we may do o mitigate this is to avoid exporting common names such as `α` from RootedTrees.jl. This would be a breaking change but semver helps. What do you think about this, @ketch?

**Comment by ketch** [comment]
It's a tradeoff between convenience for advanced users and pitfalls for novice users.

Probably because of my long experience with Python, I dislike the standard Julia approach of bringing everything into the global namespace.  I think I may start universally using "import" instead of "using" in my Julia code.  If we had done that here, the problem would be avoided (but our code would be a little more verbose).

If you don't export α from RootedTrees.jl, can users still access it via `RootedTrees.α` after `using RootedTrees`?

**Comment by ranocha** [comment]
> If you don't export α from RootedTrees.jl, can users still access it via `RootedTrees.α` after `using RootedTrees`?

Yes



> Probably because of my long experience with Python, I dislike the standard Julia approach of bringing everything into the global namespace. I think I may start universally using "import" instead of "using" in my Julia code. If we had done that here, the problem would be avoided (but our code would be a little more verbose).

Yeah, it's definitely a tradeoff. You can just use the Python way, e.g.,
```julia
julia> import RootedTrees; const rt = RootedTrees
RootedTrees

julia> t = rt.rootedtree([1, 2, 3, 4, 5])
RootedTree{Int64}: [1, 2, 3, 4, 5]
```
