### ISSUE TITLE
Elementary differential corresponding to rootedtree(Int[])

### ISSUE THREAD

**Issue by sanahsuri** [ranocha/BSeries.jl#213]
As an example, if we have the vector field $f(y)=-y$ and apply the B-series for average vector field method to it, the `evaluate` function returns 
$- \frac{h^3y}{4} + \frac{h^2y}{2} - hy + 1$
when it should return 
$- \frac{h^3y}{4} + \frac{h^2y}{2} - hy + y$
So, I think that the line in the elementary_differentials function 
```
t = rootedtree(Int[])
differentials[t] = one.(f)
```
should be 
```
t = rootedtree(Int[])
differentials[t] = u
```

**Comment by ketch** [comment]
Thanks for the suggestion.  It would be a great help if you could post the code you're using that results in the output you mention.

**Comment by sanahsuri** [comment]
Sure! 
```
# example taken from BSeries.jl API reference
avf_series = bseries(3) do t, avf_series
    if order(t) in (0, 1)
        return 1 // 1
    else
        v = 1 // 1
        n = 0
        for subtree in SubtreeIterator(t)
            v *= avf_series[subtree]
            n += 1
        end
        return v / (n + 1)
    end
end

y = symbols("y")
h = symbols("h")
var = Vector{Sym}(undef, 1)
var[1] = y
f = Vector{Sym}(undef, 1)
f[1] = -y
avf_f = evaluate(f, var, h, avf_series)
```

**Comment by ranocha** [comment]
Thanks! This looks indeed like a bug to me. So far, I have only looked at the symbolic expressions of the B-series of vector fields (with coefficient zero of the empty tree), not of numerical integrators (with coefficient unity of the empty tree). A fix should be released soon.
