### ISSUE TITLE
Overload + and - for TruncatedBSeries

### ISSUE THREAD

**Issue by ketch** [ranocha/BSeries.jl#56]
It would be nice to be able to add and subtract TruncatedBSeries (for instance, to get error coefficients easily).

**Comment by ranocha** [comment]
That's a good idea. Would you like to give it a shot to dive into the package?

**Comment by ranocha** [comment]
What would you consider to be useful when trying to add/subtract B-series of different truncation orders, @ketch? I can basically think of two approaches, both useful in different cirumstances:
- Extend the shorter B-series by zero
- Truncate the longer B-series
- Throw an error (like `DImensionMismatch`)

**Comment by ketch** [comment]
Good question. I would either truncate and throw a warning or just give an error.

**Comment by ranocha** [comment]
I decided to truncate the series in #57.

**Comment by ketch** [comment]
That makes sense.  I had forgotten that you had implemented "lazy evaluation" series that are not actually truncated.  Thanks!
