### ISSUE TITLE
Latexify returns an error for a series that is identically zero

### ISSUE THREAD

**Issue by ketch** [ranocha/BSeries.jl#94]
```
A = [0 0 0 0; 1//2 0 0 0; 0 1//2 0 0; 0 0 1 0];
b = [1//6, 1//3, 1//3, 1//6];
c = [0, 1//2, 1//2, 1];

RK4 = bseries(A, b, c, 5)
latexify(RK4 - RK4)
```
returns an error since https://github.com/ranocha/BSeries.jl/blob/5720c26e205c165bdad1beeba32b0203dcf2f0d3/src/latexify.jl#L66 assumes there is at least one entry in `expression`.  We just need to check the length of expression and return zero if expression is empty.

I would just patch this myself but I haven't figured out how to make Julia use my local copy of a package and couldn't easily find that by searching the internet.

**Comment by ranocha** [comment]
I usually use one of two options
- Open a REPL in the directory of your local clone of a package call `using Pkg; Pkg.activate("."); Pkg.update()`
- Open a temporary environment and install the development version of the package `using Pkg; Pkg.activate(temp = true); Pkg.develop("BSeries"); Pkg.add["SomeOtherPackages", "ThatYouWouldLikeToUse"])`
